import 'package:clover/core/shared/platform/app_platform.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

enum AppIcons {
  settings(iconAndroid: Icons.settings, iconIos: Icons.settings),
  map(iconAndroid: Icons.map_rounded, iconIos: CupertinoIcons.map_fill),
  ticket(iconAndroid: Icons.confirmation_number_outlined, iconIos: CupertinoIcons.ticket),
  user(iconAndroid: Icons.person, iconIos: CupertinoIcons.person_fill),
  menu(iconAndroid: Icons.menu, iconIos: CupertinoIcons.bars),
  back(iconAndroid: Icons.arrow_back, iconIos: CupertinoIcons.back),
  addShop(iconAndroid: Icons.add, iconIos: CupertinoIcons.add_circled),
  language(iconAndroid: Icons.language, iconIos: CupertinoIcons.globe),
  theme(iconAndroid: Icons.wb_sunny_outlined, iconIos: CupertinoIcons.sun_max),
  check(iconAndroid: Icons.check, iconIos: CupertinoIcons.check_mark),
  photo(iconAndroid: Icons.photo, iconIos: CupertinoIcons.photo),
  chat(iconAndroid: Icons.chat_bubble_outline_rounded, iconIos: CupertinoIcons.chat_bubble_2),
  groupOutlined(iconAndroid: Icons.group_outlined, iconIos: CupertinoIcons.person_2),
  addPhotoAlternate(
    iconAndroid: Icons.add_photo_alternate_outlined,
    iconIos: CupertinoIcons.photo_on_rectangle,
  ),
  folder(iconAndroid: Icons.folder, iconIos: CupertinoIcons.folder),
  add(iconAndroid: Icons.add, iconIos: CupertinoIcons.add),
  delete(iconAndroid: Icons.delete_outline_outlined, iconIos: CupertinoIcons.delete),
  search(iconAndroid: Icons.search, iconIos: CupertinoIcons.search),
  more(iconAndroid: Icons.more_horiz_rounded, iconIos: CupertinoIcons.ellipsis),

  // Обычные (контурные)
  like(iconAndroid: Icons.favorite_border_rounded, iconIos: CupertinoIcons.heart),
  dislike(iconAndroid: Icons.thumb_down_alt_outlined, iconIos: CupertinoIcons.hand_thumbsdown),

  // ДОБАВЛЯЕМ СЮДА: Заполненные (filled) версии для лайка и дизлайка
  likeFilled(iconAndroid: Icons.favorite_rounded, iconIos: CupertinoIcons.heart_fill),
  dislikeFilled(iconAndroid: Icons.thumb_down_alt_rounded, iconIos: CupertinoIcons.hand_thumbsdown_fill),

  comment(iconAndroid: CupertinoIcons.chat_bubble_2, iconIos: CupertinoIcons.chat_bubble_2),
  send(iconAndroid: Icons.send_rounded, iconIos: CupertinoIcons.paperplane),
  bookmark(iconAndroid: Icons.bookmark_border_rounded, iconIos: CupertinoIcons.bookmark),
  bookmarkFilled(iconAndroid: Icons.bookmark_rounded, iconIos: CupertinoIcons.bookmark_fill),
  visibility(iconAndroid: Icons.visibility_outlined, iconIos: CupertinoIcons.eye),
  visibilityOff(iconAndroid: Icons.visibility_off_outlined, iconIos: CupertinoIcons.eye_slash),
  arrowDown(iconAndroid: Icons.keyboard_arrow_down_rounded, iconIos: Icons.keyboard_arrow_down_rounded),
  arrowUp(iconAndroid: Icons.keyboard_arrow_up_rounded, iconIos: Icons.keyboard_arrow_up_rounded),
  checkBox(iconAndroid: Icons.check_box, iconIos: CupertinoIcons.check_mark),
  checkBoxBlank(iconAndroid: Icons.check_box_outline_blank, iconIos: CupertinoIcons.square),
  close(iconAndroid: Icons.close, iconIos: CupertinoIcons.xmark),
  closeRounded(iconAndroid: Icons.close_rounded, iconIos: CupertinoIcons.xmark_circle),
  copy(iconAndroid: Icons.copy_rounded, iconIos: CupertinoIcons.doc_on_doc),
  clearAll(iconAndroid: Icons.delete_sweep_outlined, iconIos: CupertinoIcons.trash),
  arrowBackRounded(iconAndroid: Icons.arrow_back_rounded, iconIos: CupertinoIcons.back),
  accessTime(iconAndroid: Icons.access_time_rounded, iconIos: CupertinoIcons.time),
  screenshot(iconAndroid: Icons.screenshot_monitor_outlined, iconIos: CupertinoIcons.camera_viewfinder),
  faceRetouching(
    iconAndroid: Icons.face_retouching_natural_outlined,
    iconIos: CupertinoIcons.person_crop_circle,
  ),
  folderOutlined(iconAndroid: Icons.folder_outlined, iconIos: CupertinoIcons.folder),
  editBrightness(iconAndroid: Icons.brightness_6_outlined, iconIos: CupertinoIcons.sun_max),
  editContrast(iconAndroid: Icons.contrast_outlined, iconIos: CupertinoIcons.circle_lefthalf_fill),
  editPalette(iconAndroid: Icons.palette_outlined, iconIos: CupertinoIcons.paintbrush),
  editWarmth(iconAndroid: Icons.wb_sunny_outlined, iconIos: CupertinoIcons.sun_max_fill),
  editFade(iconAndroid: Icons.blur_on_outlined, iconIos: CupertinoIcons.circle_grid_3x3),
  chevronLeft(iconAndroid: Icons.chevron_left_rounded, iconIos: CupertinoIcons.chevron_left),
  chevronRight(iconAndroid: Icons.chevron_right_rounded, iconIos: CupertinoIcons.chevron_right),
  checkRounded(iconAndroid: Icons.check_rounded, iconIos: CupertinoIcons.checkmark),
  searchRounded(iconAndroid: Icons.search_rounded, iconIos: CupertinoIcons.search),
  calendarToday(iconAndroid: Icons.calendar_today_outlined, iconIos: CupertinoIcons.calendar),
  schedule(iconAndroid: Icons.schedule_rounded, iconIos: CupertinoIcons.clock),
  addRounded(iconAndroid: Icons.add_rounded, iconIos: CupertinoIcons.add),
  removeRounded(iconAndroid: Icons.remove_rounded, iconIos: CupertinoIcons.minus),
  myLocation(iconAndroid: Icons.my_location_rounded, iconIos: CupertinoIcons.location_fill),
  moreVert(iconAndroid: Icons.more_vert_rounded, iconIos: CupertinoIcons.ellipsis_vertical),
  checkCircleOutline(
    iconAndroid: Icons.check_circle_outline_rounded,
    iconIos: CupertinoIcons.checkmark_circle,
  ),
  errorOutline(iconAndroid: Icons.error_outline_rounded, iconIos: CupertinoIcons.exclamationmark_circle),
  infoOutline(iconAndroid: Icons.info_outline_rounded, iconIos: CupertinoIcons.info_circle),
  locationOn(iconAndroid: Icons.location_on_outlined, iconIos: CupertinoIcons.location),
  translate(iconAndroid: Icons.translate_rounded, iconIos: Icons.translate_rounded),
  tune(iconAndroid: Icons.tune_rounded, iconIos: CupertinoIcons.slider_horizontal_3),
  arrowForward(iconAndroid: Icons.arrow_forward_rounded, iconIos: CupertinoIcons.arrow_right),
  replyOutlined(iconAndroid: Icons.reply_rounded, iconIos: CupertinoIcons.arrowshape_turn_up_left),
  editOutlined(iconAndroid: Icons.edit_outlined, iconIos: CupertinoIcons.pencil),
  archive(iconAndroid: Icons.archive_outlined, iconIos: CupertinoIcons.archivebox),
  unarchive(iconAndroid: Icons.unarchive_outlined, iconIos: CupertinoIcons.tray_arrow_up_fill),
  imageOutlined(iconAndroid: Icons.image_outlined, iconIos: CupertinoIcons.photo),
  download(iconAndroid: Icons.download_rounded, iconIos: CupertinoIcons.arrow_down_to_line),
  notificationsOutlined(iconAndroid: Icons.notifications_outlined, iconIos: CupertinoIcons.bell),
  filterList(iconAndroid: Icons.filter_list_rounded, iconIos: CupertinoIcons.line_horizontal_3_decrease),
  logout(iconAndroid: Icons.logout_rounded, iconIos: CupertinoIcons.square_arrow_right),
  lock(iconAndroid: Icons.lock_outline_rounded, iconIos: CupertinoIcons.lock),
  personRounded(iconAndroid: Icons.person_rounded, iconIos: CupertinoIcons.person_fill),
  done(iconAndroid: Icons.done_rounded, iconIos: CupertinoIcons.checkmark),
  doneAll(iconAndroid: Icons.done_all_rounded, iconIos: CupertinoIcons.checkmark_alt),
  checkCircle(iconAndroid: Icons.check_circle_rounded, iconIos: CupertinoIcons.checkmark_circle_fill),
  contentCut(iconAndroid: Icons.content_cut_outlined, iconIos: CupertinoIcons.scissors),
  calendarMonth(iconAndroid: Icons.calendar_month_outlined, iconIos: CupertinoIcons.calendar),
  loyalty(iconAndroid: Icons.loyalty_outlined, iconIos: CupertinoIcons.gift),
  payments(iconAndroid: Icons.payments_outlined, iconIos: CupertinoIcons.money_dollar_circle),
  eventAvailable(iconAndroid: Icons.event_available_outlined, iconIos: CupertinoIcons.calendar_badge_plus),
  photoCamera(iconAndroid: Icons.photo_camera_outlined, iconIos: CupertinoIcons.camera),
  cameraAlt(iconAndroid: Icons.camera_alt_rounded, iconIos: CupertinoIcons.camera_fill),
  personSearch(iconAndroid: Icons.person_search_outlined, iconIos: CupertinoIcons.search),
  linkOff(iconAndroid: Icons.link_off_outlined, iconIos: CupertinoIcons.link),
  collections(iconAndroid: Icons.collections_outlined, iconIos: CupertinoIcons.photo_on_rectangle),
  collectionsFilled(iconAndroid: Icons.collections, iconIos: CupertinoIcons.photo_fill_on_rectangle_fill),
  inventory(iconAndroid: Icons.inventory_2_outlined, iconIos: CupertinoIcons.archivebox),
  giftCard(iconAndroid: Icons.card_giftcard_outlined, iconIos: CupertinoIcons.gift),
  bookmarkOutline(iconAndroid: Icons.bookmark_outline_rounded, iconIos: CupertinoIcons.bookmark),
  personOutline(iconAndroid: Icons.person_outline_rounded, iconIos: CupertinoIcons.person),
  badge(iconAndroid: Icons.badge_outlined, iconIos: CupertinoIcons.person_crop_circle),
  mail(iconAndroid: Icons.mail_outline_rounded, iconIos: CupertinoIcons.mail),
  personOff(iconAndroid: Icons.person_off_outlined, iconIos: CupertinoIcons.person_crop_circle_badge_xmark),
  block(iconAndroid: Icons.block_rounded, iconIos: CupertinoIcons.clear),
  gridView(iconAndroid: Icons.grid_view_rounded, iconIos: CupertinoIcons.square_grid_2x2),
  event(iconAndroid: Icons.event_outlined, iconIos: CupertinoIcons.calendar),
  personRemove(
    iconAndroid: Icons.person_remove_alt_1_rounded,
    iconIos: CupertinoIcons.person_crop_circle_badge_minus,
  ),
  personAdd(iconAndroid: Icons.person_add_alt_1_rounded, iconIos: CupertinoIcons.person_add),
  description(iconAndroid: Icons.description_outlined, iconIos: CupertinoIcons.doc),
  designServices(iconAndroid: Icons.design_services_outlined, iconIos: CupertinoIcons.wrench),
  insights(iconAndroid: Icons.insights_outlined, iconIos: CupertinoIcons.chart_bar),
  settingsOutlined(iconAndroid: Icons.settings_outlined, iconIos: CupertinoIcons.gear),
  alternateEmail(iconAndroid: Icons.alternate_email_rounded, iconIos: CupertinoIcons.at),
  eventBusy(iconAndroid: Icons.event_busy_rounded, iconIos: CupertinoIcons.calendar_badge_minus),
  imageNotSupported(iconAndroid: Icons.image_not_supported_outlined, iconIos: CupertinoIcons.photo),
  folderOpen(iconAndroid: Icons.folder_open_rounded, iconIos: CupertinoIcons.folder_open),
  autoAwesome(iconAndroid: Icons.auto_awesome_outlined, iconIos: CupertinoIcons.sparkles);

  final IconData iconAndroid;
  final IconData iconIos;

  const AppIcons({required this.iconAndroid, required this.iconIos});

  IconData get icon {
    if (AppPlatform.isIOS) {
      return iconIos;
    }
    return iconAndroid;
  }
}
